### ISSUE TITLE
Docker compose quick start?

### ISSUE THREAD

**Issue by andzejsp** [icewind1991/mx-puppet-steam#45]
Hi, i cant figure out how to make this work with docker compose.

My matrix is runing on separate compose file

I created new folder:
mx-puppet-steam/
./docker-compose.yml
```yaml
version: "3.4"
services:
  mx-puppet-steam:
    hostname: mx-puppet-steam
    image: icewind1991/mx-puppet-steam
    restart: always
    volumes:
      - ./config.yaml:/data/config.yaml
     
    networks:
      - internal
networks:
  internal:
```

./config.yaml
```yaml
bridge:
  # Port to host the bridge on which your homeserver will connect to
  port: 6000
  # Address for the bridge to bind to; if running as a Docker container, you
  # probably want 0.0.0.0 here
  bindAddress: 0.0.0.0
  # Name of your homeserver
  domain: matrix.example2.com
  # URL where the bridge can connect to your homeserver
  homeserverUrl: https://matrix.example2.com

provisioning:
  # Which users are allowed to issue commands to @_steampuppet_bot
  # whitelist:
  #  - "@*:matrix.example.com"
  # A blacklist can be used instead:
  # blacklist:
  #   - "@username:matrix\\.myhomeserver\\.com"

  # Shared secret for the provisioning API for use by integration managers.
  # If this is not set, the provisioning API will not be enabled.
  #sharedSecret: random string
  # Path prefix for the provisioning API. /v1 will be appended to the prefix automatically.
  apiPrefix: /_matrix/provision

presence:
  # Bridge Steam online/offline status
  enabled: true

  # How often to send status to the homeserver in milliseconds
  interval: 5000
```

Then i run: docker compose up -d

It runs, but logs say it cant connect to my matrix. Ok, so now i have to register the bridge with my matrix homeserver.yaml.

But how? Where can i get the registration file? How to expose it from docker container? What lines do i need to add to my homeserver.yaml ???

Thanks in andvance!
